import type { Emergency } from '../types';
import { ago, daysAgo } from './time';

export const DEMO_EMERGENCIES: Emergency[] = [
  {
    id: 'EMG-1041',
    elderId: 'eld-02',
    elderName: 'Raman Kumar',
    deviceId: null,
    description: 'Help requested from basic phone',
    voiceText: null,
    voiceAudio: null,
    source: 'BASIC_PHONE',
    status: 'ACKNOWLEDGED',
    createdAt: ago(318),
    acknowledgedAt: ago(309),
    acknowledgedBy: 'Ananya Sharma',
    resolvedAt: null,
  },
  {
    id: 'EMG-1038',
    elderId: 'eld-03',
    elderName: 'Devika Menon',
    deviceId: null,
    description: 'Assistance requested via voice assistant',
    voiceText: 'I need help, please come quickly',
    voiceAudio: null,
    source: 'VOICE_ASSISTANT',
    status: 'ESCALATED',
    createdAt: daysAgo(1, 19, 42),
    acknowledgedAt: daysAgo(1, 19, 45),
    acknowledgedBy: 'Ananya Sharma',
    resolvedAt: null,
  },
  {
    id: 'EMG-1035',
    elderId: 'eld-01',
    elderName: 'Lakshmi Rao',
    deviceId: 'EA-HUB-2411',
    description: 'Help requested from HomeHub',
    voiceText: null,
    voiceAudio: null,
    source: 'HOMEHUB',
    status: 'RESOLVED',
    createdAt: daysAgo(2, 16, 12),
    acknowledgedAt: daysAgo(2, 16, 13),
    acknowledgedBy: 'Ananya Sharma',
    resolvedAt: daysAgo(2, 16, 26),
  },
  {
    id: 'EMG-1030',
    elderId: 'eld-02',
    elderName: 'Raman Kumar',
    deviceId: null,
    description: 'Help requested from basic phone',
    voiceText: null,
    voiceAudio: null,
    source: 'BASIC_PHONE',
    status: 'RESOLVED',
    createdAt: daysAgo(6, 9, 4),
    acknowledgedAt: daysAgo(6, 9, 6),
    acknowledgedBy: 'Ananya Sharma',
    resolvedAt: daysAgo(6, 9, 31),
  },
  {
    id: 'EMG-1027',
    elderId: 'eld-03',
    elderName: 'Devika Menon',
    deviceId: null,
    description: 'Help requested from basic phone',
    voiceText: null,
    voiceAudio: null,
    source: 'BASIC_PHONE',
    status: 'RESOLVED',
    createdAt: daysAgo(12, 14, 51),
    acknowledgedAt: daysAgo(12, 14, 52),
    acknowledgedBy: 'Ananya Sharma',
    resolvedAt: daysAgo(12, 15, 10),
  },
];
